/**
 * Site metadata keywords. Search engines treat matching as case-insensitive;
 * include both "Piła" and "Pila" spellings for the city name.
 */

function withLocalAndRegionVariants(phrase: string): string[] {
  const base = phrase.trim();
  if (!base) return [];

  return [
    base,
    `${base} Piła`,
    `${base} Pila`,
    `${base} Polska`,
    `${base} w Polsce`,
    `${base} Wielkopolskie`,
    `${base} Wielkopolska`,
  ];
}

function expand(phrases: readonly string[]): string[] {
  return [...new Set(phrases.flatMap(withLocalAndRegionVariants))];
}

/** Phrases that should not get geographic suffix expansion. */
const STATIC_KEYWORDS = [
  "RomanSky",
  "RomanSky Aviation",
  "Roman Jałowiecki",
  "Allegro 2000",
  "LAA ČR",
  "ÚCL",
  "EPPI",
  "lotnisko EPPI",
  "lotnisko Piła EPPI",
  "lotnisko Pila EPPI",
  "PPL",
  "PPL(A)",
  "PPL (A)",
  "ULL",
  "UL PPL",
  "LAPL",
  "LAPL(A)",
  "LAPL (A)",
  "EASA",
  "VMC",
  "Polska",
  "w Polsce",
  "Wielkopolskie",
  "Wielkopolska",
  "Wielkopolska region",
  "region Wielkopolskie",
  "region Polska",
  "Polska region",
] as const;

const LOCALIZED_BASE_PHRASES = [
  // Szkolenie i szkoła
  "szkolenie lotnicze",
  "szkolenie ultralajtem",
  "szkolenie pilotażu",
  "szkolenie na pilota",
  "szkolenie pilota",
  "szkolenie pilota samolotowego",
  "szkolenie pilotażu samolotowego",
  "szkoła lotnicza",
  "szkoła lotu",
  "szkoła latania",
  "kurs pilota",
  "kurs na pilota",
  "kurs lotniczy",
  "kurs latania",
  "nauka latania",
  "nauka pilotowania",
  "nauka pilotażu",
  "instruktor lotniczy",
  "instruktor latania",
  "lekcje lotu",
  "lekcje latania",
  "przygotowanie do licencji",
  "przygotowanie do egzaminu pilota",
  "egzamin pilota",
  "pilotaż",
  "pilotaż samolotowy",
  "jak zostać pilotem",
  "jak zostać pilotem samolotu",
  "jak nauczyć się latać",
  "certyfikat pilota",
  "licencja pilota",
  "licencja pilota samolotowego",
  "świadectwo kwalifikacji pilota",
  // ULL / ultralight
  "licencja ULL",
  "licencja pilota ultralight",
  "licencja pilota ultralajtu",
  "licencja pilota samolotów ultralekkich",
  "szkolenie ULL",
  "szkolenie pilota ultralight",
  "szkolenie pilota ultralajtu",
  "kurs pilota ultralight",
  "kurs pilota ultralajtu",
  "pilot ultralight",
  "pilot ultralajtu",
  "program czeski ULL",
  "program czeski pilota ultralight",
  "czeska licencja pilota ultralight",
  "czeska licencja ULL",
  "ULL pilot",
  "UL PPL szkolenie",
  "świadectwo kwalifikacji pilota ultralight",
  "świadectwo kwalifikacji UL PPL",
  "lot ultralajtem",
  "lot samolotem ultralekkim",
  "lot ultralight",
  "latanie ultralight",
  "latanie ultralajtem",
  "ultralajt",
  "samolot ultralekki",
  "samoloty ultralekkie",
  "ultralight",
  "ultralight aircraft",
  "samolot sportowy ultralekki",
  // LAPL
  "licencja LAPL",
  "szkolenie LAPL",
  "kurs LAPL",
  "LAPL szkolenie",
  "licencja pilota LAPL",
  "pilotaż LAPL",
  "nauka na LAPL",
  // PPL
  "licencja PPL",
  "szkolenie PPL",
  "kurs PPL",
  "PPL szkolenie",
  "PPL kurs",
  "licencja pilota PPL",
  "licencja pilota samolotowego PPL",
  "pilotaż PPL",
  "nauka na PPL",
  "nauka PPL",
  "egzamin PPL",
  "przygotowanie do PPL",
  "kurs na licencję PPL",
  "szkolenie na PPL",
  "szkolenie pilota PPL",
  "świadectwo kwalifikacji PPL",
  "pilot PPL",
  "pilot z licencją PPL",
  "PPL pilot",
  "PPL licencja",
  "PPL(A) szkolenie",
  "PPL(A) kurs",
  "PPL(A) licencja",
  // Loty i wynajem
  "lot zapoznawczy",
  "lot próbny",
  "lot demonstracyjny",
  "pierwszy lot",
  "lot samolotem",
  "lot rekreacyjny",
  "lot szkoleniowy",
  "lot z instruktorem",
  "lot solo",
  "wynajem samolotu",
  "wynajem ultralajtu",
  "wynajem samolotu sportowego",
  "wynajem samolotu ultralekkiego",
  "wynajem Allegro 2000",
  "wynajem samolotu Allegro",
  "wynajem na godziny",
  "oblatanie na typie",
  "lot sprawdzający",
  "checkout flight",
  // Ogólne awiacja / hobby
  "samolot",
  "samoloty sportowe",
  "samolot sportowy",
  "latanie",
  "latanie samolotem",
  "latanie rekreacyjne",
  "latanie sportowe",
  "latanie hobbystyczne",
  "awiacja",
  "awiacja sportowa",
  "awiacja rekreacyjna",
  "awiacja cywilna",
  "lotnictwo",
  "lotnictwo cywilne",
  "lotnictwo sportowe",
  "lotnictwo rekreacyjne",
  "lotnictwo ogólne",
  "lotnictwo amatorskie",
  "hobby lotnicze",
  "pasja lotnicza",
  "aeroklub",
  "klub lotniczy",
  "lotnisko",
  "małe lotnisko",
  "lotnisko regionalne",
  "płyta startowa",
  "ruch lotniczy",
  "procedury lotnicze",
  "nawigacja lotnicza",
  "teoria lotu",
  "teoria latania",
  "badania lotniczo-lekarskie",
  "orzeczenie lotniczo-lekarskie",
  "klasa 2 LAPL",
  "samodzielny lot",
  "lot widocznościowy",
  "warunki VMC",
] as const;

export const SITE_KEYWORDS: string[] = [
  ...new Set([...STATIC_KEYWORDS, ...expand(LOCALIZED_BASE_PHRASES)]),
];
